[package]
name = "rbtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
primitive-types = {version = "0.12.0", features=["num-traits"]}
once_cell = "1.15.0"
rand = "0.8.5"
